#MY_PROGRAM=python expect_problem2.py
MY_PROGRAM=python ../../efm279/Assignment1/problem2.py

.PHONY : clean
clean: 
	$(MY_PROGRAM) 4 1 4 2 3
	$(MY_PROGRAM) 5 1 4 2 -1 6
	$(MY_PROGRAM) 4 1 4 3 6
	$(MY_PROGRAM) 4 1 4 2 3
	$(MY_PROGRAM) 5 7 10 13 12 9
	$(MY_PROGRAM) 2 0 1
	$(MY_PROGRAM) 11 10 1 4 1 4 9 4 3 6 15 8
	$(MY_PROGRAM) 5 2 4 6 7 8
	$(MY_PROGRAM) 9 1 2 1 4 9 16 7 9 12
	$(MY_PROGRAM) 10 1 2 11 4 7 14 9 10 5 14
	$(MY_PROGRAM) 1 4
